<?php
/**
 * KTOApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OBI4wan Bots API
 *
 * Documentation for the OBI4wan BOTS API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * KTOApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KTOApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersDelete
     *
     * Delete all KTO results for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function chatbotChatbotIDKtoAnswersDelete($chatbot_id)
    {
        $this->chatbotChatbotIDKtoAnswersDeleteWithHttpInfo($chatbot_id);
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersDeleteWithHttpInfo
     *
     * Delete all KTO results for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function chatbotChatbotIDKtoAnswersDeleteWithHttpInfo($chatbot_id)
    {
        $request = $this->chatbotChatbotIDKtoAnswersDeleteRequest($chatbot_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersDeleteAsync
     *
     * Delete all KTO results for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoAnswersDeleteAsync($chatbot_id)
    {
        return $this->chatbotChatbotIDKtoAnswersDeleteAsyncWithHttpInfo($chatbot_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersDeleteAsyncWithHttpInfo
     *
     * Delete all KTO results for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoAnswersDeleteAsyncWithHttpInfo($chatbot_id)
    {
        $returnType = '';
        $request = $this->chatbotChatbotIDKtoAnswersDeleteRequest($chatbot_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatbotChatbotIDKtoAnswersDelete'
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function chatbotChatbotIDKtoAnswersDeleteRequest($chatbot_id)
    {
        // verify the required parameter 'chatbot_id' is set
        if ($chatbot_id === null || (is_array($chatbot_id) && count($chatbot_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chatbot_id when calling chatbotChatbotIDKtoAnswersDelete'
            );
        }

        $resourcePath = '/chatbot/{chatbotID}/kto_answers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($chatbot_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chatbotID' . '}',
                ObjectSerializer::toPathValue($chatbot_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersGet
     *
     * Get all KTO results
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\KTOResult[]
     */
    public function chatbotChatbotIDKtoAnswersGet($chatbot_id)
    {
        list($response) = $this->chatbotChatbotIDKtoAnswersGetWithHttpInfo($chatbot_id);
        return $response;
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersGetWithHttpInfo
     *
     * Get all KTO results
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\KTOResult[], HTTP status code, HTTP response headers (array of strings)
     */
    public function chatbotChatbotIDKtoAnswersGetWithHttpInfo($chatbot_id)
    {
        $request = $this->chatbotChatbotIDKtoAnswersGetRequest($chatbot_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\KTOResult[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\KTOResult[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\KTOResult[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\KTOResult[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersGetAsync
     *
     * Get all KTO results
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoAnswersGetAsync($chatbot_id)
    {
        return $this->chatbotChatbotIDKtoAnswersGetAsyncWithHttpInfo($chatbot_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersGetAsyncWithHttpInfo
     *
     * Get all KTO results
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoAnswersGetAsyncWithHttpInfo($chatbot_id)
    {
        $returnType = '\OpenAPI\Client\Model\KTOResult[]';
        $request = $this->chatbotChatbotIDKtoAnswersGetRequest($chatbot_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatbotChatbotIDKtoAnswersGet'
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function chatbotChatbotIDKtoAnswersGetRequest($chatbot_id)
    {
        // verify the required parameter 'chatbot_id' is set
        if ($chatbot_id === null || (is_array($chatbot_id) && count($chatbot_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chatbot_id when calling chatbotChatbotIDKtoAnswersGet'
            );
        }

        $resourcePath = '/chatbot/{chatbotID}/kto_answers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($chatbot_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chatbotID' . '}',
                ObjectSerializer::toPathValue($chatbot_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersResultKTOResultDelete
     *
     * Delete a specific KTO result for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kto_result Pass in a KTOResult to identify the KTO result. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function chatbotChatbotIDKtoAnswersResultKTOResultDelete($chatbot_id, $kto_result)
    {
        $this->chatbotChatbotIDKtoAnswersResultKTOResultDeleteWithHttpInfo($chatbot_id, $kto_result);
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersResultKTOResultDeleteWithHttpInfo
     *
     * Delete a specific KTO result for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kto_result Pass in a KTOResult to identify the KTO result. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function chatbotChatbotIDKtoAnswersResultKTOResultDeleteWithHttpInfo($chatbot_id, $kto_result)
    {
        $request = $this->chatbotChatbotIDKtoAnswersResultKTOResultDeleteRequest($chatbot_id, $kto_result);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersResultKTOResultDeleteAsync
     *
     * Delete a specific KTO result for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kto_result Pass in a KTOResult to identify the KTO result. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoAnswersResultKTOResultDeleteAsync($chatbot_id, $kto_result)
    {
        return $this->chatbotChatbotIDKtoAnswersResultKTOResultDeleteAsyncWithHttpInfo($chatbot_id, $kto_result)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatbotChatbotIDKtoAnswersResultKTOResultDeleteAsyncWithHttpInfo
     *
     * Delete a specific KTO result for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kto_result Pass in a KTOResult to identify the KTO result. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoAnswersResultKTOResultDeleteAsyncWithHttpInfo($chatbot_id, $kto_result)
    {
        $returnType = '';
        $request = $this->chatbotChatbotIDKtoAnswersResultKTOResultDeleteRequest($chatbot_id, $kto_result);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatbotChatbotIDKtoAnswersResultKTOResultDelete'
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kto_result Pass in a KTOResult to identify the KTO result. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function chatbotChatbotIDKtoAnswersResultKTOResultDeleteRequest($chatbot_id, $kto_result)
    {
        // verify the required parameter 'chatbot_id' is set
        if ($chatbot_id === null || (is_array($chatbot_id) && count($chatbot_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chatbot_id when calling chatbotChatbotIDKtoAnswersResultKTOResultDelete'
            );
        }
        // verify the required parameter 'kto_result' is set
        if ($kto_result === null || (is_array($kto_result) && count($kto_result) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kto_result when calling chatbotChatbotIDKtoAnswersResultKTOResultDelete'
            );
        }

        $resourcePath = '/chatbot/{chatbotID}/kto_answers/result/{KTOResult}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($chatbot_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chatbotID' . '}',
                ObjectSerializer::toPathValue($chatbot_id),
                $resourcePath
            );
        }
        // path params
        if ($kto_result !== null) {
            $resourcePath = str_replace(
                '{' . 'KTOResult' . '}',
                ObjectSerializer::toPathValue($kto_result),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsDelete
     *
     * Delete all questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function chatbotChatbotIDKtoQuestionsDelete($chatbot_id)
    {
        $this->chatbotChatbotIDKtoQuestionsDeleteWithHttpInfo($chatbot_id);
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsDeleteWithHttpInfo
     *
     * Delete all questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function chatbotChatbotIDKtoQuestionsDeleteWithHttpInfo($chatbot_id)
    {
        $request = $this->chatbotChatbotIDKtoQuestionsDeleteRequest($chatbot_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsDeleteAsync
     *
     * Delete all questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoQuestionsDeleteAsync($chatbot_id)
    {
        return $this->chatbotChatbotIDKtoQuestionsDeleteAsyncWithHttpInfo($chatbot_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsDeleteAsyncWithHttpInfo
     *
     * Delete all questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoQuestionsDeleteAsyncWithHttpInfo($chatbot_id)
    {
        $returnType = '';
        $request = $this->chatbotChatbotIDKtoQuestionsDeleteRequest($chatbot_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatbotChatbotIDKtoQuestionsDelete'
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function chatbotChatbotIDKtoQuestionsDeleteRequest($chatbot_id)
    {
        // verify the required parameter 'chatbot_id' is set
        if ($chatbot_id === null || (is_array($chatbot_id) && count($chatbot_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chatbot_id when calling chatbotChatbotIDKtoQuestionsDelete'
            );
        }

        $resourcePath = '/chatbot/{chatbotID}/kto_questions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($chatbot_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chatbotID' . '}',
                ObjectSerializer::toPathValue($chatbot_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsKTOquestionIDDelete
     *
     * Delete all questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kt_oquestion_id Pass in a KTOquestionID to identify the KTOquestion. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function chatbotChatbotIDKtoQuestionsKTOquestionIDDelete($chatbot_id, $kt_oquestion_id)
    {
        $this->chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteWithHttpInfo($chatbot_id, $kt_oquestion_id);
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteWithHttpInfo
     *
     * Delete all questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kt_oquestion_id Pass in a KTOquestionID to identify the KTOquestion. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteWithHttpInfo($chatbot_id, $kt_oquestion_id)
    {
        $request = $this->chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteRequest($chatbot_id, $kt_oquestion_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteAsync
     *
     * Delete all questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kt_oquestion_id Pass in a KTOquestionID to identify the KTOquestion. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteAsync($chatbot_id, $kt_oquestion_id)
    {
        return $this->chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteAsyncWithHttpInfo($chatbot_id, $kt_oquestion_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteAsyncWithHttpInfo
     *
     * Delete all questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kt_oquestion_id Pass in a KTOquestionID to identify the KTOquestion. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteAsyncWithHttpInfo($chatbot_id, $kt_oquestion_id)
    {
        $returnType = '';
        $request = $this->chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteRequest($chatbot_id, $kt_oquestion_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatbotChatbotIDKtoQuestionsKTOquestionIDDelete'
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $kt_oquestion_id Pass in a KTOquestionID to identify the KTOquestion. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function chatbotChatbotIDKtoQuestionsKTOquestionIDDeleteRequest($chatbot_id, $kt_oquestion_id)
    {
        // verify the required parameter 'chatbot_id' is set
        if ($chatbot_id === null || (is_array($chatbot_id) && count($chatbot_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chatbot_id when calling chatbotChatbotIDKtoQuestionsKTOquestionIDDelete'
            );
        }
        // verify the required parameter 'kt_oquestion_id' is set
        if ($kt_oquestion_id === null || (is_array($kt_oquestion_id) && count($kt_oquestion_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kt_oquestion_id when calling chatbotChatbotIDKtoQuestionsKTOquestionIDDelete'
            );
        }

        $resourcePath = '/chatbot/{chatbotID}/kto_questions/{KTOquestionID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($chatbot_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chatbotID' . '}',
                ObjectSerializer::toPathValue($chatbot_id),
                $resourcePath
            );
        }
        // path params
        if ($kt_oquestion_id !== null) {
            $resourcePath = str_replace(
                '{' . 'KTOquestionID' . '}',
                ObjectSerializer::toPathValue($kt_oquestion_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsPost
     *
     * Create all KTO questions
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  \OpenAPI\Client\Model\KTOQuestion[] $kto_question kto_question (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\KTOQuestion[]
     */
    public function chatbotChatbotIDKtoQuestionsPost($chatbot_id, $kto_question)
    {
        list($response) = $this->chatbotChatbotIDKtoQuestionsPostWithHttpInfo($chatbot_id, $kto_question);
        return $response;
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsPostWithHttpInfo
     *
     * Create all KTO questions
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  \OpenAPI\Client\Model\KTOQuestion[] $kto_question (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\KTOQuestion[], HTTP status code, HTTP response headers (array of strings)
     */
    public function chatbotChatbotIDKtoQuestionsPostWithHttpInfo($chatbot_id, $kto_question)
    {
        $request = $this->chatbotChatbotIDKtoQuestionsPostRequest($chatbot_id, $kto_question);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\KTOQuestion[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\KTOQuestion[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\KTOQuestion[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\KTOQuestion[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsPostAsync
     *
     * Create all KTO questions
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  \OpenAPI\Client\Model\KTOQuestion[] $kto_question (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoQuestionsPostAsync($chatbot_id, $kto_question)
    {
        return $this->chatbotChatbotIDKtoQuestionsPostAsyncWithHttpInfo($chatbot_id, $kto_question)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatbotChatbotIDKtoQuestionsPostAsyncWithHttpInfo
     *
     * Create all KTO questions
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  \OpenAPI\Client\Model\KTOQuestion[] $kto_question (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoQuestionsPostAsyncWithHttpInfo($chatbot_id, $kto_question)
    {
        $returnType = '\OpenAPI\Client\Model\KTOQuestion[]';
        $request = $this->chatbotChatbotIDKtoQuestionsPostRequest($chatbot_id, $kto_question);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatbotChatbotIDKtoQuestionsPost'
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  \OpenAPI\Client\Model\KTOQuestion[] $kto_question (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function chatbotChatbotIDKtoQuestionsPostRequest($chatbot_id, $kto_question)
    {
        // verify the required parameter 'chatbot_id' is set
        if ($chatbot_id === null || (is_array($chatbot_id) && count($chatbot_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chatbot_id when calling chatbotChatbotIDKtoQuestionsPost'
            );
        }
        // verify the required parameter 'kto_question' is set
        if ($kto_question === null || (is_array($kto_question) && count($kto_question) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kto_question when calling chatbotChatbotIDKtoQuestionsPost'
            );
        }

        $resourcePath = '/chatbot/{chatbotID}/kto_questions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($chatbot_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chatbotID' . '}',
                ObjectSerializer::toPathValue($chatbot_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($kto_question)) {
            $_tempBody = $kto_question;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chatbotChatbotIDKtoStatisticsGet
     *
     * Get the KTO statistics
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function chatbotChatbotIDKtoStatisticsGet($chatbot_id)
    {
        $this->chatbotChatbotIDKtoStatisticsGetWithHttpInfo($chatbot_id);
    }

    /**
     * Operation chatbotChatbotIDKtoStatisticsGetWithHttpInfo
     *
     * Get the KTO statistics
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function chatbotChatbotIDKtoStatisticsGetWithHttpInfo($chatbot_id)
    {
        $request = $this->chatbotChatbotIDKtoStatisticsGetRequest($chatbot_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation chatbotChatbotIDKtoStatisticsGetAsync
     *
     * Get the KTO statistics
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoStatisticsGetAsync($chatbot_id)
    {
        return $this->chatbotChatbotIDKtoStatisticsGetAsyncWithHttpInfo($chatbot_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatbotChatbotIDKtoStatisticsGetAsyncWithHttpInfo
     *
     * Get the KTO statistics
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatbotChatbotIDKtoStatisticsGetAsyncWithHttpInfo($chatbot_id)
    {
        $returnType = '';
        $request = $this->chatbotChatbotIDKtoStatisticsGetRequest($chatbot_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatbotChatbotIDKtoStatisticsGet'
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function chatbotChatbotIDKtoStatisticsGetRequest($chatbot_id)
    {
        // verify the required parameter 'chatbot_id' is set
        if ($chatbot_id === null || (is_array($chatbot_id) && count($chatbot_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chatbot_id when calling chatbotChatbotIDKtoStatisticsGet'
            );
        }

        $resourcePath = '/chatbot/{chatbotID}/kto_statistics/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($chatbot_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chatbotID' . '}',
                ObjectSerializer::toPathValue($chatbot_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ktoAnswersPost
     *
     * Post an answer to a KTOQuestion (Public)
     *
     * @param  \OpenAPI\Client\Model\KTOResult $kto_result kto_result (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\KTOResult
     */
    public function ktoAnswersPost($kto_result)
    {
        list($response) = $this->ktoAnswersPostWithHttpInfo($kto_result);
        return $response;
    }

    /**
     * Operation ktoAnswersPostWithHttpInfo
     *
     * Post an answer to a KTOQuestion (Public)
     *
     * @param  \OpenAPI\Client\Model\KTOResult $kto_result (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\KTOResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function ktoAnswersPostWithHttpInfo($kto_result)
    {
        $request = $this->ktoAnswersPostRequest($kto_result);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\KTOResult' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\KTOResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\KTOResult';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\KTOResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ktoAnswersPostAsync
     *
     * Post an answer to a KTOQuestion (Public)
     *
     * @param  \OpenAPI\Client\Model\KTOResult $kto_result (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ktoAnswersPostAsync($kto_result)
    {
        return $this->ktoAnswersPostAsyncWithHttpInfo($kto_result)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ktoAnswersPostAsyncWithHttpInfo
     *
     * Post an answer to a KTOQuestion (Public)
     *
     * @param  \OpenAPI\Client\Model\KTOResult $kto_result (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ktoAnswersPostAsyncWithHttpInfo($kto_result)
    {
        $returnType = '\OpenAPI\Client\Model\KTOResult';
        $request = $this->ktoAnswersPostRequest($kto_result);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ktoAnswersPost'
     *
     * @param  \OpenAPI\Client\Model\KTOResult $kto_result (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function ktoAnswersPostRequest($kto_result)
    {
        // verify the required parameter 'kto_result' is set
        if ($kto_result === null || (is_array($kto_result) && count($kto_result) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kto_result when calling ktoAnswersPost'
            );
        }

        $resourcePath = '/kto_answers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($kto_result)) {
            $_tempBody = $kto_result;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ktoQuestionsGet
     *
     * Get all defined KTO questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $lang_code Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\KTOQuestion[]
     */
    public function ktoQuestionsGet($chatbot_id, $lang_code)
    {
        list($response) = $this->ktoQuestionsGetWithHttpInfo($chatbot_id, $lang_code);
        return $response;
    }

    /**
     * Operation ktoQuestionsGetWithHttpInfo
     *
     * Get all defined KTO questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $lang_code Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\KTOQuestion[], HTTP status code, HTTP response headers (array of strings)
     */
    public function ktoQuestionsGetWithHttpInfo($chatbot_id, $lang_code)
    {
        $request = $this->ktoQuestionsGetRequest($chatbot_id, $lang_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\KTOQuestion[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\KTOQuestion[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\KTOQuestion[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\KTOQuestion[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ktoQuestionsGetAsync
     *
     * Get all defined KTO questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $lang_code Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ktoQuestionsGetAsync($chatbot_id, $lang_code)
    {
        return $this->ktoQuestionsGetAsyncWithHttpInfo($chatbot_id, $lang_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ktoQuestionsGetAsyncWithHttpInfo
     *
     * Get all defined KTO questions for this chatbot
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $lang_code Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ktoQuestionsGetAsyncWithHttpInfo($chatbot_id, $lang_code)
    {
        $returnType = '\OpenAPI\Client\Model\KTOQuestion[]';
        $request = $this->ktoQuestionsGetRequest($chatbot_id, $lang_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ktoQuestionsGet'
     *
     * @param  string $chatbot_id Pass in a chatbotID to identify the chatbot. (required)
     * @param  string $lang_code Pass in a chatbotID to identify the chatbot. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function ktoQuestionsGetRequest($chatbot_id, $lang_code)
    {
        // verify the required parameter 'chatbot_id' is set
        if ($chatbot_id === null || (is_array($chatbot_id) && count($chatbot_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chatbot_id when calling ktoQuestionsGet'
            );
        }
        // verify the required parameter 'lang_code' is set
        if ($lang_code === null || (is_array($lang_code) && count($lang_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lang_code when calling ktoQuestionsGet'
            );
        }

        $resourcePath = '/kto_questions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chatbot_id !== null) {
            $queryParams['chatbot_id'] = ObjectSerializer::toQueryValue($chatbot_id);
        }
        // query params
        if ($lang_code !== null) {
            $queryParams['lang_code'] = ObjectSerializer::toQueryValue($lang_code);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
