<?php
/**
 * ConversationTurnTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OBI4wan Bots API
 *
 * Documentation for the OBI4wan BOTS API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ConversationTurnTest Class Doc Comment
 *
 * @category    Class
 * @description ConversationTurn
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConversationTurnTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConversationTurn"
     */
    public function testConversationTurn()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "intent"
     */
    public function testPropertyIntent()
    {
    }

    /**
     * Test attribute "entities"
     */
    public function testPropertyEntities()
    {
    }

    /**
     * Test attribute "ask_entities"
     */
    public function testPropertyAskEntities()
    {
    }

    /**
     * Test attribute "lang_code"
     */
    public function testPropertyLangCode()
    {
    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {
    }

    /**
     * Test attribute "response"
     */
    public function testPropertyResponse()
    {
    }

    /**
     * Test attribute "entity"
     */
    public function testPropertyEntity()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "quick_replies"
     */
    public function testPropertyQuickReplies()
    {
    }

    /**
     * Test attribute "conversations"
     */
    public function testPropertyConversations()
    {
    }

    /**
     * Test attribute "params"
     */
    public function testPropertyParams()
    {
    }

    /**
     * Test attribute "preconditions"
     */
    public function testPropertyPreconditions()
    {
    }

    /**
     * Test attribute "actions"
     */
    public function testPropertyActions()
    {
    }
}
