<?php
/**
 * ConversationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OBI4wan Bots API
 *
 * Documentation for the OBI4wan BOTS API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConversationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConversationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for chatbotChatbotIDConversationsConversationIDDelete
     *
     * Delete a specific Conversations.
     *
     */
    public function testChatbotChatbotIDConversationsConversationIDDelete()
    {
    }

    /**
     * Test case for chatbotChatbotIDConversationsConversationIDGet
     *
     * Get a specific Conversations.
     *
     */
    public function testChatbotChatbotIDConversationsConversationIDGet()
    {
    }

    /**
     * Test case for chatbotChatbotIDConversationsConversationIDPut
     *
     * Returns a specific Conversations.
     *
     */
    public function testChatbotChatbotIDConversationsConversationIDPut()
    {
    }

    /**
     * Test case for chatbotChatbotIDConversationsDelete
     *
     * Delete a all Conversations.
     *
     */
    public function testChatbotChatbotIDConversationsDelete()
    {
    }

    /**
     * Test case for chatbotChatbotIDConversationsGet
     *
     * Returns all Conversations.
     *
     */
    public function testChatbotChatbotIDConversationsGet()
    {
    }

    /**
     * Test case for chatbotChatbotIDConversationsPost
     *
     * Create a specific Conversations.
     *
     */
    public function testChatbotChatbotIDConversationsPost()
    {
    }

    /**
     * Test case for chatbotChatbotIDTurnsTurnIdPut
     *
     * Modifies a turn.
     *
     */
    public function testChatbotChatbotIDTurnsTurnIdPut()
    {
    }
}
