<?php
/**
 * RegexApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OBI4wan Bots API
 *
 * Documentation for the OBI4wan BOTS API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RegexApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RegexApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for chatbotChatbotIDRegexDelete
     *
     * Delete a all training regex.
     *
     */
    public function testChatbotChatbotIDRegexDelete()
    {
    }

    /**
     * Test case for chatbotChatbotIDRegexGet
     *
     * Returns all training regex.
     *
     */
    public function testChatbotChatbotIDRegexGet()
    {
    }

    /**
     * Test case for chatbotChatbotIDRegexPost
     *
     * Create a specific training regex.
     *
     */
    public function testChatbotChatbotIDRegexPost()
    {
    }

    /**
     * Test case for chatbotChatbotIDRegexRegexIDDelete
     *
     * Delete a specific training regex.
     *
     */
    public function testChatbotChatbotIDRegexRegexIDDelete()
    {
    }

    /**
     * Test case for chatbotChatbotIDRegexRegexIDGet
     *
     * Get a specific training regex.
     *
     */
    public function testChatbotChatbotIDRegexRegexIDGet()
    {
    }

    /**
     * Test case for chatbotChatbotIDRegexRegexIDPut
     *
     * Returns a specific Regex.
     *
     */
    public function testChatbotChatbotIDRegexRegexIDPut()
    {
    }
}
