<?php
/**
 * TestExamplesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OBI4wan Bots API
 *
 * Documentation for the OBI4wan BOTS API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TestExamplesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TestExamplesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for chatbotChatbotIDRegexTestPost
     *
     * Test all regex in test examples.
     *
     */
    public function testChatbotChatbotIDRegexTestPost()
    {
    }

    /**
     * Test case for chatbotChatbotIDTestsDelete
     *
     * Delete all test examples.
     *
     */
    public function testChatbotChatbotIDTestsDelete()
    {
    }

    /**
     * Test case for chatbotChatbotIDTestsExampleIDDelete
     *
     * Delete a specific Test example.
     *
     */
    public function testChatbotChatbotIDTestsExampleIDDelete()
    {
    }

    /**
     * Test case for chatbotChatbotIDTestsExampleIDGet
     *
     * Get a specific Test example.
     *
     */
    public function testChatbotChatbotIDTestsExampleIDGet()
    {
    }

    /**
     * Test case for chatbotChatbotIDTestsExampleIDRunPost
     *
     * Run a specific test examplee.
     *
     */
    public function testChatbotChatbotIDTestsExampleIDRunPost()
    {
    }

    /**
     * Test case for chatbotChatbotIDTestsGet
     *
     * Returns all test examples.
     *
     */
    public function testChatbotChatbotIDTestsGet()
    {
    }

    /**
     * Test case for chatbotChatbotIDTestsPost
     *
     * Create a specific Test example.
     *
     */
    public function testChatbotChatbotIDTestsPost()
    {
    }

    /**
     * Test case for chatbotChatbotIDTestsRunPost
     *
     * Run all test examples.
     *
     */
    public function testChatbotChatbotIDTestsRunPost()
    {
    }
}
