<?php
/**
 * UserManagementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OBI4wan Bots API
 *
 * Documentation for the OBI4wan BOTS API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for projectProjectIDInviteGet
     *
     * Get all invites.
     *
     */
    public function testProjectProjectIDInviteGet()
    {
    }

    /**
     * Test case for projectProjectIDInviteUserPost
     *
     * Invites a person to create an account.
     *
     */
    public function testProjectProjectIDInviteUserPost()
    {
    }

    /**
     * Test case for projectProjectIDInviteeInviteIDDelete
     *
     * Delete a sepcific invite.
     *
     */
    public function testProjectProjectIDInviteeInviteIDDelete()
    {
    }

    /**
     * Test case for projectProjectIDInviteeInviteIDGet
     *
     * Get a specific invite.
     *
     */
    public function testProjectProjectIDInviteeInviteIDGet()
    {
    }

    /**
     * Test case for projectProjectIDUsersGet
     *
     * Returns all users.
     *
     */
    public function testProjectProjectIDUsersGet()
    {
    }

    /**
     * Test case for projectProjectIDUsersUserIDDelete
     *
     * Delete a specific user.
     *
     */
    public function testProjectProjectIDUsersUserIDDelete()
    {
    }

    /**
     * Test case for projectProjectIDUsersUserIDGet
     *
     * Returns a specific user.
     *
     */
    public function testProjectProjectIDUsersUserIDGet()
    {
    }

    /**
     * Test case for projectProjectIDUsersUserIDRolePut
     *
     * Modifies the role of an user.
     *
     */
    public function testProjectProjectIDUsersUserIDRolePut()
    {
    }

    /**
     * Test case for userMeGet
     *
     * Returns your user object.
     *
     */
    public function testUserMeGet()
    {
    }

    /**
     * Test case for userUserIDGet
     *
     * Returns a user.
     *
     */
    public function testUserUserIDGet()
    {
    }
}
